project:
  type: website
  output-dir: docs

website:
  title: "Aakriti Poudel"
  #favicom: nameoffolder/favicon.png
  navbar:
    #title: false
    #logo: 
    #logo-alt: 
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: resources.qmd
        text: Resources
      - icon: github
     
  page-footer: 
    left: Â© 2025, Aakriti Poudel
    right: This website is built with Quarto, R and GitHub.
    
format:
  html:
    theme: styles.scss
    toc: true
    page-layout: full
    mainfont: EB Garamond
    
editor: visual
